### ISSUE TITLE
Cannot read property 'pos' of undefined (find-3-prong-for-delta3s.js:166)

### ISSUE THREAD

**Issue by sermunar** [FlorisSteenkamp/MAT#2] opened 2019-08-23 10:07 UTC
Hi, I am facing a strange issue with calling findMats.

**Works**
I have a polygon with a hole, which represents the letter "B" (see ['B.svg' in gist](https://gist.github.com/sermunar/c3bd082be383a03ca35f74aa509a3ddf#file-b-svg)).

If I call findMats with the svg-data of "B" everything works fine and I get the expected result.

**Does not work**
Two polygons, both are representing the letter "B" like above, same shape, just duplicated and moved. (see ['BB.svg' in gist](https://gist.github.com/sermunar/c3bd082be383a03ca35f74aa509a3ddf#file-bb-svg))

I have a problem with calling findMats on the **second** polygon path, which is technically the same shape as before, just on another position.

Following error occurs:

> TypeError: Cannot read property 'pos' of undefined
  at Object.find3ProngForDelta3s (find-3-prong-for-delta3s.js:166)
    at Object.find3Prong (find-3-prong.js:44)
    at findAndAdd3Prong (find-and-add-3-prongs.js:113)
    at findAndAdd3Prongs (find-and-add-3-prongs.js:96)
    at Object.findAndAddAll3Prongs (find-and-add-3-prongs.js:23)
    at findPartialMat (find-mats.js:88)
    at Object.findMats (find-mats.js:45)

**Comment by FlorisSteenkamp** [comment] 2019-08-25 22:05
Hi sermunar.

Thanks for the bug report.

Yes, it certainly is a bug, but I couldn't reproduce it since I have made many improvements in the meantime, especially regarding robustness (via adaptive infinite precision floating point arithmetic) that is not yet published. 

I will publish an update during the upcoming week that should solve your problem.

Will keep you posted.

(The first image below is where I kept the svgs seperate and in the second one I combined them
so there is only one path element.)

![bb1](https://user-images.githubusercontent.com/10459546/63656498-6f93ad80-c749-11e9-8ac7-708944ba50c4.png)

![bb2](https://user-images.githubusercontent.com/10459546/63656514-a79af080-c749-11e9-8a78-dced010bde4b.png)

**Comment by sermunar** [comment] 2019-08-26 09:02
Hi @FlorisSteenkamp, 

thanks for your reply.

I tried to combine my "BB" paths to check if it works, but it still leads to the same error.

Just in case, I tried two different shapes and combined them, which works like a charm.

![GB](https://user-images.githubusercontent.com/21195673/63678505-a1f7e600-c7ef-11e9-8341-5d9f4677e844.PNG)

I am excited to check your update, thanks.

**Comment by sermunar** [comment] 2019-08-26 09:45
I tried some more tests with different shapes, first seperated and calling "findMats" for each path element and then the two shapes combined as single path element.

Following shapes are leading to a strange behaviour, maybe its a different bug, but I think it relates to this issue as well and maybe it helps to reproduce the core issue.

**Shape "A" and "B" seperated ([svg](https://gist.github.com/sermunar/9086a52fea0074cf5d870c226519fa96))**
findMats for shape "A" works fine, but in findMats result for shape "B" I get unexpected curves at the end. 

![A and B](https://user-images.githubusercontent.com/21195673/63681752-a96ebd80-c7f6-11e9-80c5-675114f159a8.PNG)

**Shape "A" and "B" combined ([svg](https://gist.github.com/sermunar/e8fd335fb5c525cd79250abc3d5e3c2b#file-a-and-b-combined-svg))**
findMats for the combined shape "AB" does not work and throws the same ([reported](https://github.com/FlorisSteenkamp/MAT/issues/2#issue-484447533)) error.

![A and B combined](https://user-images.githubusercontent.com/21195673/63681855-ea66d200-c7f6-11e9-9ed9-6460ef441efd.PNG)

**Comment by FlorisSteenkamp** [comment] 2019-08-26 19:01
Yes, the bugs may be related.

I am currently busy with publishing the dependent packages and then finally publishing the updated library. It should solve your issues.

**Comment by FlorisSteenkamp** [comment] 2019-08-28 02:09
Hi sermunar,

Ok, I have made the fixes and ran it through about 3000 font glyphs without issue.

Your svgs are as below:

![ab1](https://user-images.githubusercontent.com/10459546/63820265-621f2480-c8fd-11e9-8d50-05edf25794f7.png)

![ab2](https://user-images.githubusercontent.com/10459546/63820266-621f2480-c8fd-11e9-8581-d5bb781246f2.png)

Please check and see if your issues are resolved before I close.

Also, not sure if you are aware of it, but you can run the MATs through a Scale Axis Transform (SAT) to reduce the noise inherent in a MAT, e.g.

```
let mats = findMats(loops);
let S = 1.5 // or 1.1 or 5 or whatever
let sats = mats.map(mat => toScaleAxis(mat, S));
```

And thanks for the bug report!

**Comment by sermunar** [comment] 2019-08-29 08:54
Hey @FlorisSteenkamp, 

thanks for your fast responses everytime and your update 1.0.1!
Yes, I know the toScaleAxis function and I am using it as well, I just didnt mention it on this bug report to keep it clean.

Sadly I cant run findMats anymore after 1.0.1. Not a single shape is running successfully.
Following error is thrown

>TypeError: flo_gauss_quadrature_1.default is not a function
    at Object.getLoopArea (get-loop-area.js:22)
    at find-mats.js:70
    at Array.filter (<anonymous>)
    at Object.findMats (find-mats.js:49)

I realized the "flo_gauss_quadrature" is missing in the updated package.json, guess that leads to this issue.

And I have a compile error because of the changed definitions of CP-Node. Looks like the property "matCurveToNextVertex" is missing now.

![image](https://user-images.githubusercontent.com/21195673/63925112-ca7b1c80-ca49-11e9-9ce8-ced73556e389.png)

I copied this code-part for traversing the edges from your README. Could you please suggest to me how can I get the bezier data now.

Thanks a lot!

**Comment by FlorisSteenkamp** [comment] 2019-08-30 01:14
Hi Serkan

Sorry, it seems I ran the tests and then published before building first 😯.
It is fixed now.

Regarding your question about matCurveToNextVertex. This has been changed to simplify the code and remove unnecessary state. It has been superseded by getCurveToNext:

```
//let bezier = cpNode.matCurveToNextVertex;  // <- old
let bezier = getCurveToNext(cpNode);         // <- new 
```

However, I put matCurveToNextVertex back to make the code backwards compatible and added a deprecation note.

I am currently updating the documentation to reflect the above and other changes; most notably, previously one called findMats(bezierLoops, x) where x is a number of additional points per bezier curve to use to improve accuracy; however, this has now been replaced by two seperate tolerance values for better adaptive behaviour.

But of course the parameters can also be left out and you can just call findMats(bezierLoops) so the default values are used.

There is also a new function that may come in useful called simplifyMat that will remove about 70% of MAT points whilst keeping the MAT to within a specifiable tolerance, e.g. call:

```
simplifyMat(toScaleAxis(mat, scale))
```

instead of

```
toScaleAxis(mat, scale)
```

I'm excited to see the results!

**Comment by sermunar** [comment] 2019-09-02 11:57
Hey @FlorisSteenkamp,

"Houston we have **no** problem" :)

Everything works like a charm now!

![image](https://user-images.githubusercontent.com/21195673/64112696-73967f80-cd88-11e9-8e30-20460b96d8aa.png)

![image](https://user-images.githubusercontent.com/21195673/64112818-cd974500-cd88-11e9-876d-ec2194c3da0e.png)

I changed it to "getCurveToNext" as suggested and the simplification is a big improvement as well, thanks a lot!

**Closed as completed** 2019-09-02 11:59 UTC
